import type { Metadata } from "next";
import "./globals.css";
import BlobCursor from "@/components/blobCursor/BlobCursor";

export const metadata: Metadata = {
  title: "Lumebyte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {/* <link rel="alternate icon" href="favicon.ico" type="image/x-icon" /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`antialiased`}>
        <div
          id="blob"
          className="pointer-events-none fixed left-0 top-0 z-[-1] h-[300px] w-[300px] rounded-full blur-[150px] transition-all duration-[450ms] ease-out bg-gradient-to-br from-[#1100ff] via-[#1100ff4b] to-[#1900ff]"
        ></div>
        <BlobCursor />
        {children}
      </body>
    </html>
  );
}
